language: python
togliere per far runnare su travis ##################!!!!
matrix:

  include:

    - name: "Python 3.7.0 on Windows"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      #before_install:
      #  - choco install python --version 3.7.0
      #  - python -m pip install -U pip
      env:
        # - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
        - PATH=$MSBUILD_PATH:$PATH
      install:
        - reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\
        - set
        - MSBuild.exe -help
        #- set VCTargetPaths="C:\Program Files (x86)\Microsoft Visual Studio\2017\Common7\IDE\VC\VCTargets"
        # - pip install -r tests/test_requirements.txt
        - powershell -command "& { iwr https://github.com/guglielmosanchini/conda-metis/archive/master.zip -OutFile conda-metis-master.zip }"
        - powershell -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('conda-metis-master.zip', '.'); }"
        - cd conda-metis-master
        - powershell ./pre_prova.bat
        # - cmake --help
        - powershell ./vsgen.bat
        # - "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/Tools/VsDevCmd"
        # - setx VCTargetsPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\MSBuild\Microsoft\VC\v160"
        # - dotnet build build/windows/METIS.sln
        - powershell ./prova.bat
        - cd build/windows
        - MSBuild.exe METIS.sln //p:Configuration=Release
        - setx METIS_DLL C:\Users\travis\build\guglielmosanchini\ClustViz\conda-metis-master\build\windows\libmetis\Release\metis.dll

script:
  - python -m pytest

notifications:
  email: false
