name: Python package cambio

on: [push]

jobs:
  build:

    runs-on: [windows-latest]
    #runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        #os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: [3.6]

    steps:
    - name: setup-msbuild # install Visual Studio Code
      uses: microsoft/setup-msbuild@v1
    #- name: run-cmake # install cmake
    #  uses: lukka/run-cmake@v2.5
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install metis pytest
        # ls funziona!
        # pwd funziona!
        # MSBuild.exe -help funziona!
        iwr https://github.com/guglielmosanchini/conda-metis/archive/master.zip -OutFile conda-metis-master.zip
        Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('conda-metis-master.zip', '.')
        cd conda-metis-master
        ./prova.bat # moved upwards
        ./vsgen.bat
        pwd
        cd build/windows
        pwd
        MSBuild.exe METIS.sln /p:Configuration=Release
        pwd
        cd libmetis/Release
        ls
        cd ..
        cd ..
        cd ..
        cd ..
        # setx METIS_DLL D:\a\prova-windows-travis\prova-windows-travis\conda-metis-master\build\windows\libmetis\Release\metis.dll
        cd ..
        python -m pytest
      env:
        METIS_DLL: D:\a\prova-windows-travis\prova-windows-travis\conda-metis-master\build\windows\libmetis\Release\metis.dll